/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElButton: (typeof import('element-plus/es'))['ElButton']
        ElCard: (typeof import('element-plus/es'))['ElCard']
        ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
        ElCol: (typeof import('element-plus/es'))['ElCol']
        ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
        ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
        ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
        ElForm: (typeof import('element-plus/es'))['ElForm']
        ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
        ElIcon: (typeof import('element-plus/es'))['ElIcon']
        ElInput: (typeof import('element-plus/es'))['ElInput']
        ElRow: (typeof import('element-plus/es'))['ElRow']
        ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
        ElTable: (typeof import('element-plus/es'))['ElTable']
        HeaderTitle: (typeof import('./src/components/HeaderTitle/index.vue'))['default']
        HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
        RouterLink: (typeof import('vue-router'))['RouterLink']
        RouterView: (typeof import('vue-router'))['RouterView']
        SFTCard: (typeof import('./src/components/SFTCard/index.vue'))['default']
        SFTGrid: (typeof import('./src/components/SFTGrid/index.vue'))['default']
        SFTLayout: (typeof import('./src/components/SFTLayout/index.vue'))['default']
        SFTTable: (typeof import('./src/components/SFTTable/index.vue'))['default']
        SvgIcon: (typeof import('./src/components/SvgIcon/index.vue'))['default']
    }
}
